[package]
name = "lux_resolver"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
lux_core.workspace = true
id-arena.workspace = true
thiserror.workspace = true
miette.workspace = true
pep440_rs.workspace = true
pep508_rs.workspace = true
smol_str.workspace = true
version-ranges.workspace = true
smallvec.workspace = true
