//! Non-root virtual sysroot overlay engine.
//!
//! Provides isolated, unprivileged system library staging, C/C++ header integration,
//! and dynamic linker environment injection for native builds and runtime execution.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

/// Compiler and linker flags generated by the sysroot overlay.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SysrootFlags {
    /// C/C++ preprocessor include flags (e.g. `-I/path/to/sysroot/include`).
    pub cflags: String,
    /// Linker library search flags (e.g. `-L/path/to/sysroot/lib`).
    pub ldflags: String,
    /// Path to `pkgconfig` directory for `pkg-config` discovery.
    pub pkg_config_path: PathBuf,
}

/// A hermetic virtual sysroot directory structure.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SysrootOverlay {
    /// Base directory of the virtual sysroot (typically `.venv/sysroot` or CAS-cached sysroot).
    root: PathBuf,
}

impl SysrootOverlay {
    /// Creates a new `SysrootOverlay` with the specified root path.
    #[must_use]
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    /// Returns the root directory of the sysroot.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Returns the library directory (`sysroot/lib`).
    #[must_use]
    pub fn lib_dir(&self) -> PathBuf {
        self.root.join("lib")
    }

    /// Returns the C/C++ header include directory (`sysroot/include`).
    #[must_use]
    pub fn include_dir(&self) -> PathBuf {
        self.root.join("include")
    }

    /// Returns the binary executable directory (`sysroot/bin`).
    #[must_use]
    pub fn bin_dir(&self) -> PathBuf {
        self.root.join("bin")
    }

    /// Returns the pkg-config metadata directory (`sysroot/lib/pkgconfig`).
    #[must_use]
    pub fn pkgconfig_dir(&self) -> PathBuf {
        self.lib_dir().join("pkgconfig")
    }

    /// Creates all standard sysroot directories if they do not exist.
    pub fn ensure_directories(&self) -> std::io::Result<()> {
        std::fs::create_dir_all(self.lib_dir())?;
        std::fs::create_dir_all(self.include_dir())?;
        std::fs::create_dir_all(self.bin_dir())?;
        std::fs::create_dir_all(self.pkgconfig_dir())?;
        Ok(())
    }

    /// Installs a shared or static library into `sysroot/lib`.
    pub fn install_library(&self, file_name: &str, content: &[u8]) -> std::io::Result<PathBuf> {
        self.ensure_directories()?;
        let target_path = self.lib_dir().join(file_name);
        std::fs::write(&target_path, content)?;
        Ok(target_path)
    }

    /// Installs a header file into `sysroot/include`.
    pub fn install_header(&self, relative_path: &Path, content: &[u8]) -> std::io::Result<PathBuf> {
        self.ensure_directories()?;
        let target_path = self.include_dir().join(relative_path);
        if let Some(parent) = target_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&target_path, content)?;
        Ok(target_path)
    }

    /// Computes compiler and linker flags for native builds.
    #[must_use]
    pub fn compiler_flags(&self) -> SysrootFlags {
        let inc = self.include_dir();
        let lib = self.lib_dir();
        let pkg = self.pkgconfig_dir();

        let cflags = format!("-I{}", inc.display());
        let ldflags = format!("-L{}", lib.display());

        SysrootFlags {
            cflags,
            ldflags,
            pkg_config_path: pkg,
        }
    }

    /// Generates environment variable overrides for building and running with this sysroot.
    #[must_use]
    pub fn environment_overrides(&self) -> HashMap<String, String> {
        let mut env = HashMap::new();
        let lib_str = self.lib_dir().to_string_lossy().to_string();
        let inc_str = self.include_dir().to_string_lossy().to_string();
        let bin_str = self.bin_dir().to_string_lossy().to_string();
        let pkg_str = self.pkgconfig_dir().to_string_lossy().to_string();

        let flags = self.compiler_flags();

        // Standard build environment variables
        env.insert("CFLAGS".to_string(), flags.cflags.clone());
        env.insert("CPPFLAGS".to_string(), flags.cflags);
        env.insert("LDFLAGS".to_string(), flags.ldflags);
        env.insert("CPATH".to_string(), inc_str.clone());
        env.insert("LIBRARY_PATH".to_string(), lib_str.clone());
        env.insert("PKG_CONFIG_PATH".to_string(), pkg_str);

        // Windows MSVC / MinGW compatible variables
        #[cfg(target_os = "windows")]
        {
            env.insert("INCLUDE".to_string(), inc_str);
            env.insert("LIB".to_string(), lib_str.clone());

            let current_path = std::env::var("PATH").unwrap_or_default();
            env.insert("PATH".to_string(), format!("{bin_str};{lib_str};{current_path}"));
        }

        // Unix dynamic linker path injection
        #[cfg(not(target_os = "windows"))]
        {
            let current_ld = std::env::var("LD_LIBRARY_PATH").unwrap_or_default();
            let new_ld = if current_ld.is_empty() {
                lib_str.clone()
            } else {
                format!("{lib_str}:{current_ld}")
            };
            env.insert("LD_LIBRARY_PATH".to_string(), new_ld);

            let current_path = std::env::var("PATH").unwrap_or_default();
            env.insert("PATH".to_string(), format!("{bin_str}:{current_path}"));
        }

        env
    }
}
