use std::fs;
use std::path::Path;
use serde::{Deserialize, Serialize};

use super::super::error::LuxError;

/// Cryptographic hash algorithm and digest tuple.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PackageHash {
    /// Algorithm name (e.g. `"sha256"`).
    pub algorithm: String,
    /// Hex-encoded cryptographic digest.
    pub digest: String,
}

/// A pinned, fully resolved package specification stored in `lux.lock`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedPackage {
    /// Canonical package name.
    pub name: String,
    /// Exact pinned version.
    pub version: String,
    /// Transitive dependencies pinned or declared for this package.
    #[serde(default)]
    pub dependencies: Vec<String>,
    /// Cryptographic checksums of the wheel or distribution archive.
    #[serde(default)]
    pub hashes: Vec<PackageHash>,
}

/// Hermetic and reproducible `lux.lock` file format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct LuxLockfile {
    /// Lockfile specification format version.
    pub version: u32,
    /// ISO-8601 timestamp string when the lockfile was resolved.
    #[serde(rename = "created-at", default)]
    pub created_at: Option<String>,
    /// Array of all locked packages in the dependency closure.
    #[serde(rename = "package", default)]
    pub packages: Vec<LockedPackage>,
    /// Target platform triples locked for cross-platform reproducibility.
    #[serde(default)]
    pub targets: Vec<String>,
}

impl LuxLockfile {
    /// Construct a new, empty lockfile with format version 1.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            version: 1,
            created_at: None,
            packages: Vec::new(),
            targets: Vec::new(),
        }
    }

    /// Check if target platform is supported by this lockfile.
    #[must_use]
    pub fn supports_target(&self, target: &str) -> bool {
        self.targets.is_empty() || self.targets.iter().any(|t| t == target)
    }

    /// Add a target platform if not already present.
    pub fn add_target(&mut self, target: impl Into<String>) {
        let t = target.into();
        if !self.targets.contains(&t) {
            self.targets.push(t);
            self.targets.sort();
        }
    }

    /// Parse a `lux.lock` file from raw string content.
    pub fn parse(content: &str) -> Result<Self, LuxError> {
        toml::from_str(content).map_err(LuxError::from)
    }

    /// Read and parse a `lux.lock` file from disk.
    pub fn from_file(path: &Path) -> Result<Self, LuxError> {
        if !path.is_file() {
            return Err(LuxError::ManifestNotFound {
                path: path.display().to_string(),
            });
        }
        let content = fs::read_to_string(path)?;
        Self::parse(&content)
    }

    /// Serialize and write the lockfile to disk with header comments.
    pub fn save_to_file(&self, path: &Path) -> Result<(), LuxError> {
        let serialized = toml::to_string_pretty(self)?;
        let header = "# This file is automatically generated by Lux v0.1.0-alpha.\n# Manual edits may cause deterministic resolution failures.\n\n";
        let full_output = format!("{header}{serialized}");

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, full_output)?;
        Ok(())
    }

    /// Find a locked package by name (case-insensitive and normalized).
    #[must_use]
    pub fn find_package(&self, name: &str) -> Option<&LockedPackage> {
        let normalized = crate::types::normalize_name(name);
        self.packages
            .iter()
            .find(|p| crate::types::normalize_name(&p.name) == normalized)
    }

    /// Insert or update a package in the lockfile, maintaining sorted order by name.
    pub fn add_or_update_package(&mut self, package: LockedPackage) {
        let normalized = crate::types::normalize_name(&package.name);
        self.packages.retain(|p| crate::types::normalize_name(&p.name) != normalized);
        self.packages.push(package);
        self.packages.sort_by(|a, b| a.name.cmp(&b.name));
    }

    /// Remove a package from the lockfile by name.
    pub fn remove_package(&mut self, name: &str) -> bool {
        let normalized = crate::types::normalize_name(name);
        let initial_len = self.packages.len();
        self.packages.retain(|p| crate::types::normalize_name(&p.name) != normalized);
        self.packages.len() < initial_len
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lockfile_roundtrip() {
        let mut lockfile = LuxLockfile::new();
        lockfile.created_at = Some("2026-09-05T22:45:00Z".to_string());
        lockfile.add_or_update_package(LockedPackage {
            name: "requests".to_string(),
            version: "2.31.0".to_string(),
            dependencies: vec!["urllib3>=2.0".to_string()],
            hashes: vec![PackageHash {
                algorithm: "sha256".to_string(),
                digest: "abcdef1234567890".to_string(),
            }],
        });

        let serialized = toml::to_string(&lockfile).expect("serialize lockfile");
        let parsed = LuxLockfile::parse(&serialized).expect("parse lockfile");

        assert_eq!(parsed.packages.len(), 1);
        let pkg = parsed.find_package("Requests").expect("found requests");
        assert_eq!(pkg.version, "2.31.0");
        assert_eq!(pkg.dependencies.len(), 1);
        assert_eq!(pkg.hashes[0].digest, "abcdef1234567890");

        assert!(lockfile.remove_package("requests"));
        assert_eq!(lockfile.packages.len(), 0);
    }
}
