//! Lockfile export command (`lux export`).

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::Instant;
use miette::Result;

use lux_core::manifest::lockfile::LuxLockfile;
use crate::ui::Status;

/// Execute `lux export` to export `lux.lock` to pip requirements format.
pub fn run_export(
    format: &str,
    output: Option<PathBuf>,
    no_hashes: bool,
) -> Result<()> {
    let start = Instant::now();
    let cwd = env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let lock_path = find_lockfile(&cwd)
        .ok_or_else(|| miette::miette!("No lux.lock found in {} or any parent directory. Run `lux resolve` or `lux add` first.", cwd.display()))?;

    let lockfile = LuxLockfile::from_file(&lock_path)
        .map_err(|e| miette::miette!("Failed to read {}: {e}", lock_path.display()))?;

    if format != "requirements-txt" && format != "requirements.txt" {
        return Err(miette::miette!(
            "Unsupported export format '{format}'. Supported formats: 'requirements-txt'"
        ));
    }

    let mut lines = Vec::new();
    lines.push("# This file was autogenerated by Lux via `lux export`.".to_string());
    lines.push("# Deterministic dependency closure with cryptographic integrity verification.\n".to_string());

    let mut packages = lockfile.packages;
    packages.sort_by(|a, b| a.name.cmp(&b.name));

    for pkg in &packages {
        if no_hashes || pkg.hashes.is_empty() {
            lines.push(format!("{}=={}", pkg.name, pkg.version));
        } else {
            let mut pkg_line = format!("{}=={}", pkg.name, pkg.version);
            for hash in &pkg.hashes {
                use std::fmt::Write as _;
                let _ = write!(pkg_line, " \\\n    --hash={}:{}", hash.algorithm, hash.digest);
            }
            lines.push(pkg_line);
        }
    }

    lines.push(String::new());
    let content = lines.join("\n");

    if let Some(out_path) = output {
        fs::write(&out_path, &content)
            .map_err(|e| miette::miette!("Failed to write {}: {e}", out_path.display()))?;
        Status::completed(
            "Exported",
            &format!("{} package(s) -> {}", packages.len(), out_path.display()),
            Some(start.elapsed()),
        );
    } else {
        let mut stdout = std::io::stdout();
        stdout
            .write_all(content.as_bytes())
            .map_err(|e| miette::miette!("Failed writing to stdout: {e}"))?;
    }

    Ok(())
}

/// Helper function to search for `lux.lock` starting from `dir` and moving upwards.
fn find_lockfile(dir: &Path) -> Option<PathBuf> {
    let mut current = dir.to_path_buf();
    loop {
        let candidate = current.join("lux.lock");
        if candidate.is_file() {
            return Some(candidate);
        }
        if !current.pop() {
            return None;
        }
    }
}
