[package]
name = "lux_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "lux_cli"
path = "src/lib.rs"

[[bin]]
name = "lux"
path = "src/main.rs"

[dependencies]
lux_core.workspace = true
lux_resolver.workspace = true
lux_cache.workspace = true
lux_sysroot.workspace = true

clap.workspace = true
clap_complete.workspace = true
miette.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
ring.workspace = true
reqwest.workspace = true
pep508_rs.workspace = true

[dev-dependencies]
tempfile.workspace = true
